### ISSUE TITLE
Improve container credentials retrieval using workflow compute environment 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#223]
Wave retrieves the container credentials to be used, querying Tower credentials for `container-reg` provider and looking for a matching registry name. 

This is convenient for users that rely on registries such as Docker or Quay. However, it can be suboptimal for users that store container images in the cloud registry provided by the cloud vendor associated with by the pipeline execution. 

The goal of this issue is to extend the credentials retrieval mechanism in such a way that when there isn't a credentials match for the required repositories, the system fallbacks to the crendianls associated with the compute environment used by the pipeline execution.

The above approach should take place only when the container repository is hosted in the same platform where the pipeline executed e.g. AWS ECR and the execution platform is AWS Batch

**Comment by munishchouhan** [comment]
I have tested using local compute, got this
` INFO  i.s.w.service.CredentialServiceImpl - ------Found compute env: local-platform and credentials: null`
I will test with aws-batch next

**Comment by robnewman** [comment]
@munishchouhan What is the status of this issue? Thanks.

**Comment by munishchouhan** [comment]
> @munishchouhan What is the status of this issue? Thanks.

Dev part is completed, but I have to test it on dev because not possible to test in local 
Testing of this feature requires some special setup, where credentials can be used to create compute and access ECR
I tried multiple times to test in dev using tower dev user but no luck
so to summarise its testing is pending, once that done paolo can review it
