### ISSUE TITLE
Build cache can remain in invalid status

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#299]
If the status record of a container fails to be updated in the Redis DB, the container build can remain in an inconsistent status until the record is not evicted by the cache itself. 

More in detail for some reason the build `863ab08f7b3f34e8` failed to update the completion status remaining in the following status 

```
{"exitStatus":0,"id":"863ab08f7b3f34e8","startTime":"2023-09-26T09:48:05.237384977Z"}
```

Following build request for the same Dockerfile resulted in the same build ID, hit the build cache. The following log was produced 

```
wave-67b49bd9dc-fp9nf wave-app 14:50:27.821 [ForkJoinPool.commonPool-worker-2] DEBUG i.s.wave.core.RegistryProxyService - Credentials for route path=195996028523.dkr.ecr.eu-west-1.amazonaws.com/wave/build:863ab08f7b3f34e8; user=null; wsp=null => RegistryCredentials[username=AWS; password=eyJ****]
wave-67b49bd9dc-fp9nf wave-app 14:50:27.957 [ForkJoinPool.commonPool-worker-2] INFO  i.s.w.s.b.ContainerBuildServiceImpl - == Hit build cache for request: BuildRequest[id=863ab08f7b3f34e8; targetImage=195996028523.dkr.ecr.eu-west-1.amazonaws.com/wave/build:863ab08f7b3f34e8; user=User(id:1, userName:pditommaso, email:paolo.ditommaso@gmail.com); dockerFile=FROM alpine  (more omitted); condaFile=null; spackFile=null]
wave-67b49bd9dc-fp9nf wave-app 14:50:29.520 [io-executor-thread-112] INFO  i.s.w.c.RegistryProxyController - > Request [HEAD] /v2/wt/da4e0340e876/wave/build/manifests/863ab08f7b3f34e8
wave-67b49bd9dc-fp9nf wave-app 15:05:40.131 [io-executor-thread-120] INFO  i.s.w.c.RegistryProxyController - > Request [GET] /v2/wt/da4e0340e876/wave/build/manifests/863ab08f7b3f34e8
wave-67b49bd9dc-fp9nf wave-app 15:06:59.744 [io-executor-thread-117] WARN  io.seqera.wave.ErrorHandler - Build of container '195996028523.dkr.ecr.eu-west-1.amazonaws.com/wave/build:863ab08f7b3f34e8' timed out - Request: HEAD /v2/wt/da4e0340e876/wave/build/manifests/863ab08f7b3f34e8
```

In a nutshell

1. the build request is skipped because the record is found in the cache 

https://github.com/seqeralabs/wave/blob/82682b63b450de654e0cb033c35270562df71b59/src/main/groovy/io/seqera/wave/service/builder/ContainerBuildServiceImpl.groovy#L275-L275

2. Then the docker client pull the container with the following request 

```
GET /v2/wt/da4e0340e876/wave/build/manifests/863ab08f7b3f34e8
```

3. Since the record is found, wave keep in the wait loop, see here 

https://github.com/seqeralabs/wave/blob/82682b63b450de654e0cb033c35270562df71b59/src/main/groovy/io/seqera/wave/service/builder/ContainerBuildServiceImpl.groovy#L140-L144

and here 

https://github.com/seqeralabs/wave/blob/82682b63b450de654e0cb033c35270562df71b59/src/main/groovy/io/seqera/wave/service/builder/BuildStore.groovy#L101-L101

**Comment by munishchouhan** [comment]
I think we should check if the build is succeeded instead of only checking if its null in here
https://github.com/seqeralabs/wave/blob/82682b63b450de654e0cb033c35270562df71b59/src/main/groovy/io/seqera/wave/service/builder/ContainerBuildServiceImpl.groovy#L274

`if( ret2.succeeded() ) `
or else submit build request

**Comment by pditommaso** [comment]
Likely solved by https://github.com/seqeralabs/wave/pull/421
