### ISSUE TITLE
Replace Java HttpClient by Micronaut/Netty HTTP client

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#305]
The Wave [ProxyClient](https://github.com/seqeralabs/wave/blob/e5b7f694e41285081fb3fbde519c0daed8e630a2/src/main/groovy/io/seqera/wave/proxy/ProxyClient.groovy#L47-L47) relies on the Java HTTP client to fetch container manifest and download binary content (blob layers).

However, the Java client is affected by several problem that makes unreliable especially when pulling large binary content (see [here](https://bugs.openjdk.org/browse/JDK-8308364) and [here](https://bugs.openjdk.org/browse/JDK-8308144)). 

The goal of this issue is to replace the Java HTTP client with the one provided my Micronaut which in [turn relies on Netty](https://docs.micronaut.io/latest/guide/#lowLevelOrHighLevel). 

Update: possible solution could be provided by [this PR](https://github.com/openjdk/jdk/pull/14159).

**Comment by marcodelapierre** [comment]
Resolved by https://github.com/seqeralabs/wave/pull/358 (Micronaut streaming client)
