### ISSUE TITLE
Inconsistent status on build failure

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#312]
A container build status will be reported as failed when:

1. A build is launched and it does not complete successfully due to a non-permanent error condition 
2. A following build attempt is completed successfully

**Comment by munishchouhan** [comment]
@pditommaso is it related to https://github.com/seqeralabs/wave/issues/299?

**Comment by pditommaso** [comment]
It may, but not 100% sure

**Comment by pditommaso** [comment]
This has been solved by https://github.com/seqeralabs/wave/pull/421
