### ISSUE TITLE
Update to Micronaut 4.x

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#314]
Micronant 4.5.x bring some nice new feature and improvement it should be explored the impact to update Wave backend to this version

**Comment by munishchouhan** [comment]
PR created in libseqera, because this upgrade needs upgrade lib-mail too
https://github.com/seqeralabs/libseqera/pull/7

**Comment by pditommaso** [comment]
This can be resumed, right?

**Comment by munishchouhan** [comment]
> This can be resumed, right?

this is blocked by https://github.com/seqeralabs/libseqera/pull/7/files
