### ISSUE TITLE
[spack] add back reuse capability to spack

### ISSUE THREAD

**Issue by bebosudo** [seqeralabs/wave#315]
As I showed [in this comment](https://github.com/seqeralabs/devops-backlog/issues/269#issuecomment-1761890445) I think we should enable the reuse capability in spack to make it reuse existing packages as much as possible.

Quoting from that comment:
> This means that if a customer asks for spack package X today they will get package version chcksmv1, but if they ask for X again tomorrow they'll receive version chcksmv2, which we'll need to build again from scratch, taking time, defeating the purpose of having a cache and probably hitting the wave timeout.

Currently we're removing the reuse capability  from spack, I'm not sure why:
https://github.com/seqeralabs/wave/blob/f562ef9c637f49a45a66147ce9a2219514d47916/src/main/resources/io/seqera/wave/spack/spack-builder-dockerfile.txt#L26
(similarly for singularity)

Here's an example: we boot up a spack container and we specifically install an old version of a package, with the same current spack settings we use in our dockerfile:

```console
[alberto@fedora]$ docker run spack/ubuntu-jammy:v0.20.0
root@9a002a3ef21e:/home/alberto/seqera/repos/spack# sed -i -e 's;compilers:;compilers::;' -e 's;^ *flags: *{};    flags:\n      cflags: -O3\n      cxxflags: -O3\n      fflags: -O3;' /root/.spack/linux/compilers.yaml
root@9a002a3ef21e:/home/alberto/seqera/repos/spack# spack config add config:install_tree:/opt/software
root@9a002a3ef21e:/home/alberto/seqera/repos/spack# spack config add concretizer:unify:true
root@9a002a3ef21e:/home/alberto/seqera/repos/spack# spack config add concretizer:reuse:false
root@9a002a3ef21e:/home/alberto/seqera/repos/spack# spack config add packages:all:target:[x86_64]
root@9a002a3ef21e:/home/alberto/seqera/repos/spack# spack info libiconv
...
Safe versions:  
    1.17    https://ftpmirror.gnu.org/libiconv/libiconv-1.17.tar.gz
    1.16    https://ftpmirror.gnu.org/libiconv/libiconv-1.16.tar.gz

root@9a002a3ef21e:/home/alberto/seqera/repos/spack# spack install libiconv@1.16
==> libiconv: Successfully installed libiconv-1.16-lwkdmjlfctyenahkzndgrohbznwux5k4
  Stage: 1.18s.  Autoreconf: 0.00s.  Configure: 7.61s.  Build: 4.66s.  Install: 0.30s.  Post-install: 0.02s.  Total: 13.80s
[+] /opt/software/linux-ubuntu22.04-x86_64/gcc-11.3.0/libiconv-1.16-lwkdmjlfctyenahkzndgrohbznwux5k4
```

Let's say that an updated version is now available: if we now try to check what spack would install, it would try to install the newest package possible, version 1.17:

```console
root@9a002a3ef21e:/home/alberto/seqera/repos/spack# spack spec -Il libiconv
 -   lrivueh  libiconv@1.17%gcc@11.3.0 cflags="-O3" cxxflags="-O3" fflags="-O3"  build_system=autotools libs=shared,static arch=linux-ubuntu22.04-x86_64
```

But if we ask spack to reuse all possible dependencies and even the package itself, it'll do it:

```console
root@9a002a3ef21e:/home/alberto/seqera/repos/spack# spack spec -Il --reuse libiconv
[+]  lwkdmjl  libiconv@1.16%gcc@11.3.0 cflags="-O3" cxxflags="-O3" fflags="-O3"  build_system=autotools libs=shared,static arch=linux-ubuntu22.04-x86_64
```

If we remove the `reuse:false` concretization option spack defaults to only reusing the dependencies ([docs](https://spack.readthedocs.io/en/latest/build_settings.html) - can't be appreciated here because there are no dependencies, try repeating the example with e.g. bzip2):

```console
root@9a002a3ef21e:/home/alberto/seqera/repos/spack# spack config rm concretizer:reuse:false
root@9a002a3ef21e:/home/alberto/seqera/repos/spack# spack spec -Il libiconv
 -   lrivueh  libiconv@1.17%gcc@11.3.0 cflags="-O3" cxxflags="-O3" fflags="-O3"  build_system=autotools libs=shared,static arch=linux-ubuntu22.04-x86_64
```

In order to make spack reuse more aggressively all possible dependencies and even the package itself, we should instead use
```console
&& spack config add concretizer:reuse:true \
```
Which has the same effect of passing `--reuse` at the install cmd line.

@munishchouhan let me know if you need more help, and please tag me on the PR.

**Comment by pditommaso** [comment]
Tagging again @marcodelapierre

**Comment by marcodelapierre** [comment]
Apologies for the wait folks.

I agree, I think adding `reuse` is a good idea.

Context: in my long running  HPCon-prem experience with Spack I had advocated for no reuse, to maximise reproducibility of build of the whole software stack. In fact, with reuse on, changing the order of package build may change the final status of the software stack. Reuse off avoids this.

Our Wave use case is different though. Each Wave usage instance is independent from other instances, and users should be prescriptive in requesting the desired software features within the `process.spack`. Anything that is not specified there falls back to our Wave configuration, and I think it is fair to turn `reuse` on to maximise cache usage, minimise build time, minimise storage reqs for the cache.  Perhaps the documentation should declare this behaviour for transparency.

I will propose a docs edit in the PR.

**Comment by marcodelapierre** [comment]
Just one note for us, as a side product of reusing packages, any test of running the same pipeline over time may result in slightly different package variants being selected, as a consequence of the reuse strategy. This should not be alarming, but may require care in thinking about what we are testing.
