### ISSUE TITLE
Feature request: Support docker digests

### ISSUE THREAD

**Issue by ewels** [seqeralabs/wave#331]
It would be great if Wave could support container images that specify a digest as tag (see [docker docs](https://docs.docker.com/engine/reference/run/#imagedigest)).

For example, `image@sha256:<hash>`:

```bash
docker run alpine@sha256:9cacb71397b640eca97488cf08582ae4e4068513101088e9f96c9814bfda95e0 date
```

**Comment by pditommaso** [comment]
TLDR; it cannot be done. 

Long explanation, the docker digest is essentially the sha256 checksum of the JSON manifest file that defines the content of the container. 

When requesting a container via Wave, the container is augmented to include the task custom scripts and the Fusion driver (if enabled). This essentially requires manipulating the original JSON manist to add one or more binary layers and therefore the resulting container will have a different checksum from the requested one.

**Comment by ewels** [comment]
Aha, ok this makes sense. And we can't use it to identify the image pre-augmentation or anything?

**Comment by marcodelapierre** [comment]
Phil, can you provide a bit of context as to when it would be beneficial? and/or when there is a need for referring to the digest rather than the tag, or even just going the "Wave way" and focusing on the required software rather than the underlying container.

Thanks,

**Comment by ewels** [comment]
It's a very limited request (single support ticket, the only time I've heard it mentioned). I guess that it comes from being used to being as specific as possible about image contents to ensure maximum reproducibility / traceability. Tags can be overwritten / modified, a sha cannot.

**Comment by marcodelapierre** [comment]
Thanks Phil. I also have seen that usage of sha's in the past, fair enough.

I am wondering whether we should reason with the customer around how Wave proposes to tackle the reproducibility / traceability issue: by renouncing to trace container artefacts, and focusing instead on how the software is built and deployed: package version X, installed (with its dependencies) using Conda/Spack version Y. 

Note how the specific container image may be cleared out of the Wave cache anyway at some point, and future rebuilds may have differing shasums if some of the underlying dependencies change (conda version, dependency versions...).
What makes the NF pipeline still reproducible is the pipeline definition itself, that includes description of which packages are required along with that of the pipeline tasks. 

Do you think it might be a value adding conversation for that customer?

**Comment by pditommaso** [comment]
Freeze mode should provide an alternative to achieve this requirement

**Comment by marcodelapierre** [comment]
> Freeze mode should provide an alternative to achieve this requirement

🥶

**Comment by k-florek** [comment]
I just ran into this issue as we have been playing with wave now to see how it works with our workflows. We have established it as a best practice to reference images using the sha256 digest. Using the digest is how we can prove to regulating agencies that the tools and dependencies remain consistent and locked down. Using just the docker tag carries a risk that the docker image could have changed under the tag which can result in reproducibility issues and a serious concern when running workflows in a diagnostic setting.

@ewels idea of calling the image pre-augmentation would be nice if feasible

**Comment by pditommaso** [comment]
That's possible by enabling `wave.freeze = true`, see [here](https://www.nextflow.io/docs/latest/wave.html#advanced-settings) for details

**Comment by ewels** [comment]
I think that we can close this issue to be honest. Freeze effectively solves the reproducibility question and I don't think that we will implement the hash tag thing any time soon.. Agreed?

**Comment by pditommaso** [comment]
Agreed

**Comment by gwright99** [comment]
Should there be a documentation update to make it clear this method isn't supported? Trying to reduce the number of future requests we may get about the same thing.
