### ISSUE TITLE
Investigate updating to Gradle 8.4

### ISSUE THREAD

**Issue by marcodelapierre** [seqeralabs/wave#335]
@pditommaso  @munishchouhan  any comment on this one?

At this stage I am only suggesting because I see Gradle 8.3 is not compatible with Java 21 (analogous compatibility was resolved by Paolo for Nextflow a couple of weeks ago).

**Comment by pditommaso** [comment]
It should work. In nextflow we are using gradle 8.4 

https://github.com/nextflow-io/nextflow/blob/4c6f2e8541afae3a3960b04e71aaa62f744c1866/gradle/wrapper/gradle-wrapper.properties#L3-L3

**Comment by munishchouhan** [comment]
@pditommaso @marcodelapierre So, should we update to Java 21 and Gradle 8.4?

**Comment by pditommaso** [comment]
Don't think Java 21 is required for Gradle 8.4

**Comment by marcodelapierre** [comment]
Other way round, VS Code is telling me that, because I am using Java 21 in the machine, I need at least Gradle version 8.4

**Comment by munishchouhan** [comment]
use sdkman to switch between jdk version

**Comment by marcodelapierre** [comment]
I know, low priority on this, but sooner or later we'll need to move forward with versions anyway :-)
