### ISSUE TITLE
Revisit support for Spack target architectures, to match Nextflow inputs

### ISSUE THREAD

**Issue by marcodelapierre** [seqeralabs/wave#336]
We want to make sure we are able to build Wave Containers with target micro-architectures that are relevant/useful to the service.

Current status:
- Nextflow: see https://github.com/nextflow-io/nextflow/issues/4523
- Wave backend currently restricts legal Spack platform values to either `x86_64` or `aarch64` (or equivalent), see https://github.com/seqeralabs/wave/blob/master/src/main/groovy/io/seqera/wave/util/SpackHelper.groovy#L54-L63

TO-DO: 
- Nextflow side: see https://github.com/nextflow-io/nextflow/issues/4523
- Wave backend side: wider list of targets to be accepted (at minimum, add `x86_64_v3`)
- Wave backend side: diversify between container platform required for container builder and target for Spack commands in containerfile
  - eg see https://github.com/seqeralabs/wave/blob/master/src/main/groovy/io/seqera/wave/core/ContainerPlatform.groovy#L103-L114
  - likely need to have distinct attributes for container platform vs spack target

For reference, list of Spack supported targets as of today: https://spack.readthedocs.io/en/latest/basic_usage.html#support-for-specific-microarchitectures

**Comment by pditommaso** [comment]
Spack support is Sunsetting #531
