### ISSUE TITLE
Implement Pull-through cache mode

### ISSUE THREAD

**Issue by marcodelapierre** [seqeralabs/wave#338]
Posting original thoughts by @pditommaso  on this topic.

- In 70-80% of requests, Wave only redirects to the bucket, and then the Docker client performs a direct layer pull from object storage
- However for some containers this path is not taken, and Wave has to "serve" the whole binary payload, which causes issues
- Ideally we should create a cache and make use of it at download time
- https://docs.docker.com/docker-hub/mirror/
- https://github.com/seqeralabs/wave/blob/d29f217066c17834112e65e6c6bf8ebd77763c28/src/main/groovy/io/seqera/wave/controller/RegistryProxyController.groovy#L243-L257

**Comment by pditommaso** [comment]
Solved by #359
