### ISSUE TITLE
Making sure kaniko doesn't cache the spack base image

### ISSUE THREAD

**Issue by bebosudo** [seqeralabs/wave#347]
In the kaniko options we are using [`--cache=true`](https://github.com/seqeralabs/wave/blob/f6924f4a9c56fc774fc4062262970bafd8f08253/src/main/groovy/io/seqera/wave/service/builder/BuildStrategy.groovy#L64) to cache the layers.
Since we're architecting a system to replace the spack base image daily, kaniko shouldn't cache the base image, or it won't ever use the updated spack base image.
It seems that in order to cache base images an external process (the "warmer") should make the images available: https://github.com/GoogleContainerTools/kaniko#caching-base-images

Can you confirm that we're not populating the cache for base images?

CC @marcodelapierre

**Comment by marcodelapierre** [comment]
@munishchouhan  to comment here about setup / test logs

**Comment by bebosudo** [comment]
Looks good to me, thanks for checking this. Closing the issue.
