### ISSUE TITLE
Prevent NPE  on Spack build

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#353]
When a Spack `specs` attribute is missing the following NPE error is thrown 

```
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "spack" is null
```

The critical point is [this line](https://github.com/seqeralabs/wave/blob/3619dbb402c97f3d3e1be09c2868baede3e62fd0/src/main/groovy/io/seqera/wave/util/RegHelper.groovy#L224-L224).

A validation error should be added to report an actionable error message to the user

**Comment by marcodelapierre** [comment]
@pditommaso  what do you mean for "Spack spec is missing"?

A spack directive is empty? or the spec is not available within Spack recipes? Can you provide more context to this scenario? Thank you

**Comment by pditommaso** [comment]
A spack file can be 

```
spack:
  specs:
  - star@2.5.4a
  - bwa@0.7.15
```


therefore I thinking it can be happen both  `spack:` and `specs:` are missing. In any case the way to handle this is to write the unit test to validate the fix instead of guessing.

**Comment by marcodelapierre** [comment]
Thanks Paolo, now it is clearer for me
