### ISSUE TITLE
Wave + Singularity configuration - issues w/ pulling images

### ISSUE THREAD

**Issue by JosephLalli** [seqeralabs/wave#374]
I'm trying to use Singularity w/ Fusion in a Dockerized Nextflow environment on a grid computing cluster. While there's a lot of ways that can go wrong, right now I'm getting the same exact error as #252, despite the solution introduced in #259. I am using Nextflow version 23.12.0-edge.

I'm trying to run the hello pipeline. My command is nextflow run hello -config test.config, with test.config containing:

apptainer {
    enabled=true
}
fusion {
  enabled = true
  exportStorageCredentials = true
}
wave {
    enabled = true
}
tower {
    *tower login credentials*
}

I have a feeling that there is something wrong with how I am configuring this, but based off of the documentation on how to use fusion I think I'm doing this right. In particular, I'm not sure if there is a requirement for Singularity-native base images, what good repositories exist for them, or how I can automatically convert dockerfiles to native singularity files when necessary. How do I know if "container = 'quay.io/nextflow/bash' will pull a singularity-native image?
I don't see any documentation of wave/fusion and singularity, despite the apparent support based off of development activity here. Is this feature not finished? Or is there something I should check to debug this?

Thanks,
Joe

**Comment by munishchouhan** [comment]
@JosephLalli Thanks for raising the issue
here is the documentation for singularity
https://www.nextflow.io/docs/latest/container.html#singularity

you can use following config to enable singulairty
```
singularity {
    enabled = true
}
```

**Comment by munishchouhan** [comment]
@JosephLalli you can use docker.io to store your singularity images
you can check out wave-cli to build singularity images 
https://github.com/seqeralabs/wave-cli

**Comment by pditommaso** [comment]
Singularity it's a bit more tricky. Usually nextflow tries to convert Docker images to SIF format using a `singularity pull` command ahead of the container execution, but this does not work well with Wave. 

As of version 23.12.0-edge it has been added the option `singularity.ociAutoPull=true` that allows singularity to access directly the container without the need of a separate pull command. Please give a try to it

**Comment by JosephLalli** [comment]
Other potential causes of the issue that I've tried to address:

As I read [nextflow's wave documentation](https://www.nextflow.io/docs/latest/wave.html), I need to set up wave to upload the generated images to an online repository. I've tried running with the additional configuration options:

> wave.freeze = true
> wave.build.repository = 'docker.io/jlalli/wave_images'

but Wave objects that it does not have push permissions. Supplying my username and password using the environmental variables SINGULARITY_DOCKER_USERNAME and SINGULARITY_DOCKER_PASSWORD did not solve the problem. Note that I am trying to run Nextflow in a docker container, and I don't have the docker daemon running inside the container, so I cannot test if docker push ____ works appropriately.

I feel very in the weeds here, like I'm missing something fundamental.

**Comment by munishchouhan** [comment]
add these credentials in Seqera platform (tower) and wave will pick from there

**Comment by JosephLalli** [comment]
Ah, thank you! That appears to have solved the problem. 

Just so I have a good understanding of what's happening under the hood: Nextflow is downloading quay.io/nextflow/bash from quay.io, converting to an sif, adding a fusion layer, and uploading the resulting recipe to docker?

Is there any way to store the resulting sif in a local folder cache?
