### ISSUE TITLE
Fix support for SurrealDB 1.x

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#381]
When using the latest stable version of Surreal DB the following test is failing 

https://github.com/seqeralabs/wave/blob/c495d80c1654785627cc5e7337354d8b995a06d2/src/test/groovy/io/seqera/wave/service/persistence/impl/SurrealPersistenceServiceTest.groovy#L289-L324

**Comment by munishchouhan** [comment]
Working on it now

**Comment by marcodelapierre** [comment]
@pditommaso  @munishchouhan  closed by https://github.com/seqeralabs/wave/pull/388  right?

**Comment by pditommaso** [comment]
Yes
