### ISSUE TITLE
Add support for Cloudflare WAF token authentication 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#382]
When using Cloudflare CDN to cache the image layers the use of AWS S3 pre-signed URLs are infective to prevent unauthorised access. See here for more [context](https://community.cloudflare.com/t/add-cdn-in-front-of-r2-private-bucket-with-custom-domain/598774). 

An alternative approach consists implementing a Cloudflare WAF (web application firewall) token authentication. 

The token should be added to the target resource to be valid using the syntax `/some/path?verify=<token>`

An example how to generate the hmac token are reported in the Cloudflare docs 

https://developers.cloudflare.com/waf/custom-rules/use-cases/configure-token-authentication/#option-2-configure-using-waf-custom-rules

**Comment by munishchouhan** [comment]
Does this PR https://github.com/seqeralabs/wave/pull/383 close this issue, or does something else need to be done?

**Comment by pditommaso** [comment]
Yes
