### ISSUE TITLE
Backward compatibility with SurrealDB 1.0-beta8

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#387]
Latest versions of SurrealDB introduce some breaking changes with the datastore binary format. 

Unfortunately, the migration process looks to not work properly as well, [see here](https://github.com/surrealdb/surrealdb/issues/2359).

To goal of this issue it allow the use of the latest versions of SurrealDB introduced by https://github.com/seqeralabs/wave/pull/380, without breaking the compatibility with the existing data.

The overall idea consists of using a new DB deployment using the version 1.1.x. that it will be used a primary datastore for any read and write operation, and use the old instance only in read mode, as fallback when a record in not found in the primary DB.

**Comment by marcodelapierre** [comment]
@pditommaso  @munishchouhan  closed by https://github.com/seqeralabs/wave/pull/388  right?
