### ISSUE TITLE
Store and display Wave usage metrics 

### ISSUE THREAD

**Issue by munishchouhan** [seqeralabs/wave#390]
Metrics:

1. Number of container build requests by user (including anonymous as a user)
2. Number of container build requests by IP
3. Number of container build requests by image name
4. Total Number of container build requests on a given range of days
5. Number of successful container build requests on a given range of days
6. Number of  pull requests  by user (including anonymous as a user)
7. Number of pull requests by IP 
8. Number of pull requests by imagename
9. Number of pull requests
10. Number of distinct users accessed Wave on a given range of days
11. Number of distinct IPs accessed Wave on a given range of days

cc @drewdipalma @ewels 
```[tasklist]
### Tasks
- [x] Design
- [x] DB for metrics
- [x] API for metrics
```

**Comment by ewels** [comment]
Thanks @munishchouhan!

Could you elaborate on what engaging users are please? And what are we counting with "Number of distinct IPs" - Unique IPs doing what?

**Comment by ewels** [comment]
Also is this the internal Seqera-only metrics? Or user facing?

If internal then we already have superset for a DB and UI and everything I think. So not sure that we need most of the tasks, it should just be a case of saving the metrics to the existing setup, I think..

**Comment by pditommaso** [comment]
This is a mini-dashboard, irrespective of Seqera. Wave has not have direct access to Superset. Instead Superset will need to fetch from Wave

**Comment by munishchouhan** [comment]
> Could you elaborate on what engaging users are please? And what are we counting with "Number of distinct IPs" - Unique IPs doing what?

@ewels I have made the description more clearer, please check

**Comment by ewels** [comment]
Ok - so who / where is this hosted? Who will the users be? Who will be able to access it?
