### ISSUE TITLE
Allow the customisation of container image names

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#395]
Wave allow building container images by providing either Dockerfile and Conda packages, and push the resulting image to a repository (not registry) name provided by user e.g. `quay.io/some/repo`. 

When doing so the resulting container images will have the following naming convention when using a dockerfile

```
quay.io/some/repo:<HASH>
```

and  

```
quay.io/some/repo:<CONDA PACKAGE NAME>--<HASH>
```

Where `<HASH>` represents the checksum of the Dockerfile used to build the container. 

The following approach has some drawbacks:

1. when using a dockerfile the resulting image name/tag is still anonymous i.e. there's no way to infer what it does containes 
2. when using more than one Conda package, the resulting tag list all package names becoming difficult to read
3. all contained images are pushed to the same container repository i.e. `quay.io/some/repo` resulting into a collection of heterogeneous packages. 

The goal of this issue is to provide the user the ability to specify the target repository name the should extend the information of the target build repository byt introducing a new `imageName` attribute that would work the following: 

1. `buildRepository: "quay.io/some/repo"` and `imageName: <empty>` uses the current behavior 
2. `buildRepository: "quay.io/some/repo"` and `imageName: "foo"` results in the container name `quay.io/some/repo/foo:<HASH>`
3. `buildRepository: "quay.io/some/repo"` and `imageName: "foo/bar"` results in the container name `quay.io/some/repo/foo/bar:<HASH>`
4.  `buildRepository: "quay.io"` and `imageName: "foo/bar"` results in the container name `quay.io/foo/bar:<HASH>`

Possible drawbacks: 

* A malicious user could use this approach, especially 4., to override container images in arbitrary  repository

**Comment by munishchouhan** [comment]
@pditommaso should I start working on it?

**Comment by ewels** [comment]
Great! I think that this will be really helpful, I much prefer having separate docker repos for different software tools rather than one for everything..

> A malicious user could use this approach, especially 4., to override container images in arbitrary repository

I don't entirely follow this. For Wave to push an image to eg. quay.io the use has to have access credentials. If they have credentials then they can override container images already, no? Or do you mean that this could lead to people doing this by accident?

**Comment by ewels** [comment]
The public registry is a special case, so we may need some special behaviour here to control scoping above the root level.

**Comment by munishchouhan** [comment]
Three PRs have been created to achieve this in Wave.

1. https://github.com/seqeralabs/libseqera/pull/13
2. https://github.com/seqeralabs/wave-cli/pull/57
3. https://github.com/seqeralabs/wave/pull/408

I have tested the functionality locally. 

<img width="1375" alt="Screenshot 2024-02-22 at 14 54 31" src="https://github.com/seqeralabs/wave/assets/6575288/d1e09982-0798-4f49-aa86-7049c11cf69c">

**Comment by munishchouhan** [comment]
TODO:
1. Validate custom target name

**Comment by pditommaso** [comment]
I'm starting to question if this is really needed. The build repository attribute should be used to control the image name. 

Instead [here](https://github.com/seqeralabs/wave-cli/issues/45) the request is turn off the name discovery from the conda package names. 

On the other hand, it also required to use the conda package name(s) as the target image name(s). 

I think we should introduce an option that allows controlling the image auto naming e.g. 

* `none`: the build repository is used as target image name and the container is is used as tag e.g. `community.seqera.io/library/foo:12345` 
* `tag-prefix` (default): the package name is added used to prefix the tag (the current implementation
* `image-suffix`: the package name is added to the build repository

**Comment by munishchouhan** [comment]
I was also thinking about the prefix because if in nextflow, we cannot provide image name for every container, but we can provide a prefix which can be used for all the containers for that pipeline.

**Comment by pditommaso** [comment]
Solved as described [here](https://github.com/seqeralabs/wave/issues/395#issuecomment-2059492650) by #460
