### ISSUE TITLE
Add a functionality to evict a container token request

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#409]
When a container request is submitted to Wave, a unique token is associated with it and this token is included in the ephemeral container name returned by the system e.g. 

```
wave.seqera.io/wt/46f707c3fbc1/library/alpine:latest
```

The container is accessible for the lifespan of the token defined by the configuration setting named `wave.tokens.cache.duration`. 

The goal of this feature is to provide a way to evict the token from the Redis cache ahead of the "natural" eviction, either via an API call and UI. 

#### Deletion endpoint 

Add the endpoint `DELETE /container-token/{token}` to evict the toke from the token cache. The endpoint should require the user authentication via `@Secured(SecurityRule.IS_AUTHENTICATED)` annotation 

#### Deletion UI 

Add to the Container request page a *Delete* action at the bottom of the page. The action should only be rendered when the user is authenticated.

**Comment by pditommaso** [comment]
I believe the browser displays a basic credentials form if you try to access a password protected URI

**Comment by pditommaso** [comment]
We talked about this, let's follow this approach: 

1. The [container view page](https://github.com/seqeralabs/wave/blob/6325b25c0095c0efe39e943f915808a64f9256dc/src/main/groovy/io/seqera/wave/controller/ViewController.groovy#L100-L100) just container a button to the bottom to evict the container request (no auth required) 
2. The button links to a new page `/view/containers/{token}/delete` (auth \*required*) 
3. This page just a confirmation button to the user
4. if the user Confirms the operation the `DELETE /container-token/{token}` is invoked

**Comment by munishchouhan** [comment]
@pditommaso `DELETE /container-token/{token}` is also authenticated, so when a user confirms to delete, we still need a username and password to delete it

**Comment by munishchouhan** [comment]
> @pditommaso `DELETE /container-token/{token}` is also authenticated, so when a user confirms to delete, we still need a username and password to delete it

@pditommaso please ignore

**Comment by munishchouhan** [comment]
@pditommaso this is how the eviction looks now:
UI:

https://github.com/seqeralabs/wave/assets/6575288/9b22d2e7-d19b-4e69-bf6f-2d526489f8c4

Image pulling before and after eviction:
```
munish.chouhan@Munishs-MacBook-Pro ~ % wave -i hrma017/dev:7cd3153c70d18711 --wave-endpoint https://1979a79cf58a.ngrok.app --tower-token='eyJ0aWQiOiAyfS5jNDk0MjhlNjAwNWViMzI2OGRmZGM0Mjg5MzlmYzI5M2ZjNTFmZDQz' --tower-endpoint='http://localhost:8008/api'
1979a79cf58a.ngrok.app/wt/3c84a84e01e9/hrma017/dev:7cd3153c70d18711
munish.chouhan@Munishs-MacBook-Pro ~ % docker pull 1979a79cf58a.ngrok.app/wt/3c84a84e01e9/hrma017/dev:7cd3153c70d18711
7cd3153c70d18711: Pulling from wt/3c84a84e01e9/hrma017/dev
Digest: sha256:5ff3a7b87e590f16d093a889d03c24c7c21367acd49ab70e43d8900bd33e2531
Status: Downloaded newer image for 1979a79cf58a.ngrok.app/wt/3c84a84e01e9/hrma017/dev:7cd3153c70d18711
1979a79cf58a.ngrok.app/wt/3c84a84e01e9/hrma017/dev:7cd3153c70d18711
munish.chouhan@Munishs-MacBook-Pro ~ % docker pull 1979a79cf58a.ngrok.app/wt/3c84a84e01e9/hrma017/dev:7cd3153c70d18711
Error response from daemon: unknown: Unknown Wave container for token '3c84a84e01e9'
```

**Comment by munishchouhan** [comment]
@pditommaso how about this?
<img width="1190" alt="Screenshot 2024-02-27 at 15 38 22" src="https://github.com/seqeralabs/wave/assets/6575288/d0187b16-1e0b-4dae-9b89-1f780a3c7d8e">

**Comment by pditommaso** [comment]
Much better

**Comment by munishchouhan** [comment]
<img width="880" alt="Screenshot 2024-02-27 at 15 42 01" src="https://github.com/seqeralabs/wave/assets/6575288/1f9d49ef-7483-4665-b4f7-c7a5188cf4f3">

**Comment by pditommaso** [comment]
Can the same "Danger zone" section added to the latter page?

**Comment by pditommaso** [comment]
Yes!
