### ISSUE TITLE
Invalid entrypoint propagation

### ISSUE THREAD

**Issue by jordeu** [seqeralabs/wave#412]
## Description

Given an image that has a composed entry point like this:
```
$  docker pull docker.io/vanvalenlab/deepcell-applications:0.4.1
...
$  docker inspect docker.io/vanvalenlab/deepcell-applications:0.4.1 | grep -v null | grep -A3 Entrypoint
            "Entrypoint": [
                "python",
                "run_app.py"
            ],
```

When we overwrite the entrypoint with Wave:

```
$ docker run -it $(wave -i docker.io/vanvalenlab/deepcell-applications:0.4.1 --config-entrypoint='bash') -c "env | grep WAVE_ENTRY_CHAIN"
...
WAVE_ENTRY_CHAIN=python
```

The original entrypoint should be **fully** propagated using the environment variable `WAVE_ENTRY_CHAIN`.

## Current result

Only the first part of the entrypoint is propagated (`WAVE_ENTRY_CHAIN=python`)

## Expected result

The whole command separated by blank spaces is propagated (`WAVE_ENTRY_CHAIN="python run_app.py"`)

**Comment by pditommaso** [comment]
This 

https://github.com/seqeralabs/wave/blob/master/src/main/groovy/io/seqera/wave/core/ContainerAugmenter.groovy#L328-L331

**Comment by munishchouhan** [comment]
@pditommaso so should be change 
https://github.com/seqeralabs/wave/blob/f8cfdcc17aa2f88cf12fc408f9c3e14c5ed47b78/src/main/groovy/io/seqera/wave/core/ContainerAugmenter.groovy#L311
to
`return value.join(' ')`

**Comment by pditommaso** [comment]
The problem converting a list to a string is not safe, because there could be value containing blanks. Wrapping in quotes could help, but it should be considered that the value can container the quote itself .. 

@jordeu Also is Fusion able to handle correctly multi-option entry point via `WAVE_ENTRY_CHAIN` ?

**Comment by pditommaso** [comment]
@munishchouhan It may be enough to use [Escape.cli](https://github.com/seqeralabs/wave/blob/master/src/main/groovy/io/seqera/wave/util/Escape.groovy#L79-L81) to render the list as a safe string

**Comment by jordeu** [comment]
I've done a small test to check how it looks like a "shell" entrypoint.

From this `Dockerfile`:
```
FROM ubuntu
ENTRYPOINT "echo Hola"
```

We get this entrypoint:
```
$ docker inspect jordeu/entrypointtest:nolist | grep -v null | grep -A4 Entrypoint
            "Entrypoint": [
                "/bin/sh",
                "-c",
                "\"echo Hola\""
            ],
```

**Comment by jordeu** [comment]
Not sure that this multi-option entrypoint is supported by Fusion, but I'm going to check and fix it if needed.

**Comment by munishchouhan** [comment]
@pditommaso using Escape.cli()
its returning `'/bin/sh -c '"echo Hola"''`  for the above example, but expected is `'/bin/sh -c "echo Hola"' `

**Comment by munishchouhan** [comment]
> @pditommaso using Escape.cli() its returning `'/bin/sh -c '"echo Hola"''` for the above example, but expected is `'/bin/sh -c "echo Hola"' `

this works fine with simple join
We need to list out the different cases and have utility method for that

**Comment by jordeu** [comment]
Given that this encoding is a bit custom. We may consider encoding it as a JSON list. This will make the encoding and decoding easier.

**Comment by pditommaso** [comment]
Um, what about backward compability with existing Fusion clients

**Comment by jordeu** [comment]
> Um, what about backward compability with existing Fusion clients

To keep backward compatibility, I would return a single string if the list contains only one element; otherwise return the list JSON formatted.

**Comment by pditommaso** [comment]
The old version would not try to run the json payload as a command? you mean that ion any case it's broken?

**Comment by jordeu** [comment]
> The old version would not try to run the json payload as a command? you mean that ion any case it's broken?

Yes it will, and it will fail. But, yes, in any case entrypoints with more than one entry are already broken (and failing in an unpredictable way).

**Comment by pditommaso** [comment]
Ok, let's do this way. Therefore when the entrypoint is a list with more than 1 element it will be rendered as a json wrapped into single quotes eg.. 

```
WAVE_ENTRY_CHAIN='["/some","/command"]'
```
