### ISSUE TITLE
Improve evict container feedback layout

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#418]
The Look & feel of the feedback message when eviting a containing request is too basic. Ideally it should be rendered in place of the red box 

 
<img width="839" alt="Screenshot 2024-03-12 at 12 03 10" src="https://github.com/seqeralabs/wave/assets/816968/99f076d2-599f-4e44-b430-fb64e44ab443">

**Comment by munishchouhan** [comment]
ok, I will change the layout

**Comment by munishchouhan** [comment]
@pditommaso should we only show the Danger zone when the token is present in the cache?

**Comment by pditommaso** [comment]
It does not really matter, it's enough to make it nicer

**Comment by munishchouhan** [comment]
@pditommaso is this ok?

https://github.com/seqeralabs/wave/assets/6575288/beecca8e-0c28-4a6a-a71d-109357cb1270

**Comment by pditommaso** [comment]
Much better 👍
