### ISSUE TITLE
Create build status endpoint 

### ISSUE THREAD

**Issue by munishchouhan** [seqeralabs/wave#420]
Add a new endpoint in builds to check the status on any build using buildid
`
GET /v1alpha1/builds/{buildId}/status`

**class design**
```
class BuildStatus {
   static enum Status { PENDING, COMPLETED }
   String id
   Status status
   Boolean succeeded
   Instant created
   Duration duration
}
```

cc: @pditommaso @ewels

**Comment by munishchouhan** [comment]
PR in libseqera created 
https://github.com/seqeralabs/libseqera/pull/18

**Comment by pditommaso** [comment]
I've removed the `FAILED` in the Status enum because that can be inferred by the `succeeded` flag

**Comment by pditommaso** [comment]
Not this feature requires this PR
