### ISSUE TITLE
Metrics Service based on Redis

### ISSUE THREAD

**Issue by munishchouhan** [seqeralabs/wave#426]
Redis metrics service. The current implementation is flawed. We need to redesign from scratch: 

- Recover the implementation based on [MeterRegistry](https://github.com/seqeralabs/wave/commit/c8d55b8712bc52d9d19b5da6077e9bcce0a7fa3a)
- Instead of `MeterRegistry` use Redis counters, see [HINCRBY](https://redis.io/commands/hincrby/)

      1. Use a hash with those keys:
      2. pulls/d/YYYY-MM-DD
      3. pulls/o/<organization>
      4. pulls/o/<organization>/d/YYYY-MM-DD
      5. fusion/d/YYYY-MM-DD
      6. fusion/o/<organization>
      7. fusion/o/<organization>/d/YYYY-MM-DD
      8. builds/d/YYYY-MM-DD
      9. builds/o/<organization>
      10. builds/o/<organization>/d/YYYY-MM-DD

- For the query controller, instead of using a date range, just use a punctual date

**Comment by marcodelapierre** [comment]
@munishchouhan @pditommaso is it possible to have some additional context around this issue, ideally in the first comment? Thank you

**Comment by pditommaso** [comment]
The problem is that the current approach counts the API requests to get a container token, and the same token can be used multiple times to pull the same container. Therefore it's not counting the pulls

**Comment by pditommaso** [comment]
True, you can start using it using that branch as baseline for this
