### ISSUE TITLE
Add inspect enpoint  in wave

### ISSUE THREAD

**Issue by munishchouhan** [seqeralabs/wave#446]
We have a inspect service in wave, this issue is to expose that service through an API endpoint. Currently its being used by wave-cli using --inspect option.

**Comment by marcodelapierre** [comment]
This would be useful, for instance, for nf-core functionalities that need to retrieve the URI of a Wave image 

(see https://github.com/seqeralabs/wave/issues/443)

**Comment by munishchouhan** [comment]
We already have endpoint for inspect `/v1alpha1/inspect` I will add documentation for this

**Comment by marcodelapierre** [comment]
Thank you Munish, closing this one, mentioned the doc requirement in #443
