### ISSUE TITLE
BuildRequest refactor 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#455]
Currently the `containerId` and the `targetImage` attributes are computed by the `BuildRequest` constructor, see below

https://github.com/seqeralabs/wave/blob/6a3c4c79ee070c5add510794406d11bc622513b0/src/main/groovy/io/seqera/wave/service/builder/BuildRequest.groovy#L146-L152

However, there isn't a real value on doing that and this makes the tests complex. The goal of this issue is the refactor the `BuildRequest` constructor so that both the `containerId` and `targetImage` attributes are computed before creating the `BuildRequest` object and passed as regular parameters. 

The BuildRequest constructor should be changed to a *canonical* constructor i.e. constructor arguments are specified in the same order as they are declared in the class 

https://github.com/seqeralabs/wave/blob/6a3c4c79ee070c5add510794406d11bc622513b0/src/main/groovy/io/seqera/wave/service/builder/BuildRequest.groovy#L54-L139

**Comment by pditommaso** [comment]
@munishchouhan let's put this in the fast track please

**Comment by munishchouhan** [comment]
> @munishchouhan let's put this in the fast track please

@pditommaso ok sure
