### ISSUE TITLE
Wave container builds failing due to private ECR path modifications

### ISSUE THREAD

**Issue by benemead** [seqeralabs/wave#483]
Hi there,

In the past couple hours, all of our seqera cloud-launched nextflow pipelines utilizing wave containers have been failing to build.

These are pipelines we routinely run, with wave containers stored in our private AWS ECR e.g.: `[acct].dkr.ecr.[region].amazonaws.com/wave_build`.

I’ve noticed in the wave build logs that the path to the container image is being modified to a path that does not exist and that we do not specify, with `/library/` being inserted e.g.: `[acct].dkr.ecr.[region].amazonaws.com/library/wave_build:[image]` This results in a permissions error because this path does not exist in our private repo.

I see the latest tagged release had this function added in [ContainerHelper.groovy](https://github.com/seqeralabs/wave/blame/df4e2af206841a1a11eec0ec1e88170beaa4b30c/src/main/groovy/io/seqera/wave/util/ContainerHelper.groovy):

```groovy
static protected String normaliseRepo(String value) {
        if( !value )
            return value
        final parts = value.tokenize('/')
        if( parts.size()>2 )
            return value
        if( parts.size()==1 ) {
            return parts[0] + '/library/build'
        }
        else {
            return parts[0] + '/library/' + parts[1]
        }
    }
```

Maybe it's being applied too broadly? Appreciate any help!

**Comment by munishchouhan** [comment]
@benemead thanks for reporting the issue, we will look into it

**Comment by munishchouhan** [comment]
@benemead can you please share your nextflow log or a reproducer?

**Comment by pditommaso** [comment]
@benemead, apologies for the problem; I think you are right. That change seems to have unexpected side effects. It has been reverted.

**Comment by benemead** [comment]
Looks like we're back to working! Thank you both!!
