### ISSUE TITLE
Cleanup of complete blob transfer jobs

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#485]
The blob cache uses Kubernetes pods (and [job in the future](https://github.com/seqeralabs/wave/issues/475)) to upload  them in the cache storage. 

Those jobs should be deleted when the upload is completed successfully. 

It could be used the same strategy used for build job 

https://github.com/seqeralabs/wave/blob/4adb5e2e7b66de8f373d2729ac69b01429b66a44/src/main/groovy/io/seqera/wave/service/cleanup/CleanupStrategy.groovy#L36-L36

**Comment by munishchouhan** [comment]
cleanup strategy is used for deleting build context

https://github.com/seqeralabs/wave/blob/a400f914b16b8601f9e06211d3713164dcfd090a/src/main/groovy/io/seqera/wave/service/builder/BuildStrategy.groovy#L40-L42

I think jobs and pods cleaning should be done in k8s

**Comment by pditommaso** [comment]
Likely here, if the upload is ok 

https://github.com/seqeralabs/wave/blob/master/src/main/groovy/io/seqera/wave/service/blob/impl/KubeTransferStrategy.groovy#L51-L57

**Comment by munishchouhan** [comment]
we can use `ttlSecondsAfterFinished`
https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically

**Comment by pditommaso** [comment]
The custom strategy would allow deleting immediately successful jobs and retail failed one. Don't think it's possible using `ttlSecondsAfterFinished`

**Comment by pditommaso** [comment]
Solved by #568 and #595
