### ISSUE TITLE
Update accesstoken when refreshing jwt token 

### ISSUE THREAD

**Issue by munishchouhan** [seqeralabs/wave#509]
there may be a bug in the refresh token mechanism
looking here, it seems that uses always the same accessToken
https://github.com/seqeralabs/wave/blob/6758c739328d55ee6c1681f0cbefe1f616c4ed42/src/main/groovy/io/seqera/wave/tower/client/connector/TowerConnector.groovy#L208-L208
but I think when the refresh token request is submitted also the  accessToken should be updated

In nextflow both of them are updated

https://github.com/nextflow-io/nextflow/blob/dec2b5ea571d963d69350e8db0803aaeba0a436a/plugins/nf-tower/src/main/io/seqera/tower/plugin/TowerXAuth.groovy#L94-L110

**Comment by pditommaso** [comment]
Solved by #512
