### ISSUE TITLE
Unable to fetch container digest 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#527]
Once a container image is built, the digest checksum is acquired to be stored in the build metadata. 

https://github.com/seqeralabs/wave/blob/ec268a9f4671e0f31516f59bff5b02a6722e4fd2/src/main/groovy/io/seqera/wave/service/builder/KubeBuildStrategy.groovy#L106-L107

However, in some cases, this is failing with a 401 error code (Unauthorized). See below

```
2024-06-13 11:47:31.044	09:47:31.044 [io-executor-thread-50] WARN  i.s.wave.core.RegistryProxyService - Unable to retrieve digest for image 'xxx.dkr.ecr.us-west-2.amazonaws.com/some-name:xxxxxxxxx' -- response status=401; headers:

  content-length=15
  content-type=text/plain; charset=utf-8
  date=Thu, 13 Jun 2024 09:47:30 GMT
  docker-distribution-api-version=registry/2.0
  sizes=
  www-authenticate=Basic realm="https://xxxx.dkr.ecr.us-west-2.amazonaws.com/",service="ecr.amazonaws.com"

``` 

This should not happen because the ProxyClient when a 401 is returned, should retry the (head) requested with a new auth token 

https://github.com/seqeralabs/wave/blob/ec268a9f4671e0f31516f59bff5b02a6722e4fd2/src/main/groovy/io/seqera/wave/proxy/ProxyClient.groovy#L268-L272

**Comment by pditommaso** [comment]
Worth noticing the logic for GET is different form the HEAD one 

https://github.com/seqeralabs/wave/blob/ec268a9f4671e0f31516f59bff5b02a6722e4fd2/src/main/groovy/io/seqera/wave/proxy/ProxyClient.groovy#L190-L193

**Comment by munishchouhan** [comment]
I can see in the logs that, we only start getting this error after the deployment of version 1.8

**Comment by munishchouhan** [comment]
> I can see in the logs that, we only start getting this error after the deployment of version 1.8

ok because it is added in that version

**Comment by pditommaso** [comment]
I've found the problem. Opening a PR soon
