### ISSUE TITLE
Add Redis health watcher

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#535]
Redis is a critical component in the Wave architecture. 

It should be added a backend component that monitors in the background the following Redis health metrics: 

1. Free memory space as a percentage of the total. 
2. CPU usage percentage.
3. Cache hit rate. 

Those values should be reported in the log with INFO level. When some metrics exceed a configurable threshold, they should be reported as WARN level.

**Comment by munishchouhan** [comment]
Can we use Prometheus to monitor Redis?
https://medium.com/@MetricFire/how-to-monitor-redis-performance-819125702401

**Comment by munishchouhan** [comment]
@pditommaso Can we use Prometheus to monitor Redis?
https://medium.com/@MetricFire/how-to-monitor-redis-performance-819125702401

**Comment by pditommaso** [comment]
Make sense

**Comment by munishchouhan** [comment]
Closing in favour of grafana dashboard
