### ISSUE TITLE
Should wave cleanup failed builds pods and succeeded transfer pods?

### ISSUE THREAD

**Issue by bebosudo** [seqeralabs/wave#566]
Abandoned wave builds pods recently caused several node disk pressure alerts (see [thread](https://seqera.slack.com/archives/C05C55E9GHW/p1720597332318809)), which made me write down a [cleanup procedure](https://www.notion.so/seqeralabs/Runbooks-2a2a68ec568f49218946dbd9c0586f48?p=f1b56912d7434f629caceb950b76886c) in our notion runbooks.

Should wave cleanup failed pods after a while? Currently in prod there are pods that successfully completed more than 2 months ago, or failed build pods from a month ago:

```console
[alberto@fedora]$ k -n wave-build get pod --sort-by=.metadata.creationTimestamp
NAME                        READY   STATUS      RESTARTS   AGE
transfer-9ffcd0cbc6711eed   0/1     Completed   0          73d
transfer-bed778e834948a0e   0/1     Completed   0          73d
transfer-e55a8672d151107f   0/1     Completed   0          73d
transfer-50e99103a0dec647   0/1     Completed   0          73d
transfer-611ae3b007e2d1fe   0/1     Completed   0          73d
...
transfer-0b131dc04e9a3c2a   0/1     Completed   0          53d
transfer-fccf98933fc03ac1   0/1     Completed   0          53d
build-204718099de3bd5e-1    0/1     Error       0          27d
build-847126e7a72ace0b-1    0/1     Error       0          27d
build-5c4ddc972496f248-1    0/1     Error       0          27d
...
```

Failed/completed pods still consume storage resources, because they could be restarted anytime. On the node which triggered the high disk usage I found several build containers weighing 30, 40 and even 50 GB each, since somebody was building a CUDA-capable container, and they are taking up half of the 800 GB local nvme disk.

Don't know if this may be related to this other issue I found: https://github.com/seqeralabs/wave/issues/485

CC @HLWiencko

**Comment by bebosudo** [comment]
Related: https://github.com/seqeralabs/wave/pull/568

**Comment by pditommaso** [comment]
Actually requires this https://github.com/seqeralabs/wave/pull/576
