### ISSUE TITLE
Remove ContentReader and ContentReaderFactory classes

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#583]
[The ContentReaderFactory](https://github.com/seqeralabs/wave/blob/fc436f7c8f080817e4b24440df691fee4408e197/src/main/groovy/io/seqera/wave/storage/reader/ContentReaderFactory.java#L28-L28) class,   [ContentReader](https://github.com/seqeralabs/wave/blob/fc436f7c8f080817e4b24440df691fee4408e197/src/main/groovy/io/seqera/wave/storage/reader/ContentReader.java#L30-L30) interface and corresponding implementation classes are not used any more. They should removed from the codebase.

**Comment by munishchouhan** [comment]
should we replace it with other in https://github.com/seqeralabs/wave/blob/master/src/main/groovy/io/seqera/wave/storage/LazyDigestStore.java?
or remove LazyDigestStore and its usage
https://github.com/seqeralabs/wave/blob/fc436f7c8f080817e4b24440df691fee4408e197/src/main/groovy/io/seqera/wave/controller/RegistryProxyController.groovy#L201

**Comment by pditommaso** [comment]
I think `LazyDigestStore` is not used anymore, hence should be removed
