### ISSUE TITLE
Wave containers containing `conda-forge::perl` fail to buld

### ISSUE THREAD

**Issue by kchaung-lilly** [seqeralabs/wave#586]
I am trying to build some Wave containers that contain Perl. However, when I use the conda-forge::perl=STUB package, the build will fail.

Here is an example of a build ID of a failed container build: e331129e3475236a_2

**Comment by munishchouhan** [comment]
@kchaung-lilly thanks for reporting the issue, we will check it out and get back to you

**Comment by munishchouhan** [comment]
conda-forge::perl=STUB package doesnot exist
```
20.26 error    libmamba Could not solve for environment specs
20.26     The following package could not be installed
20.26     └─ perl STUB*  does not exist (perhaps a typo or a missing channel).
20.27 critical libmamba Could not solve for environment specs
```

**Comment by munishchouhan** [comment]
@kchaung-lilly I have created an image using wave cli for conda-forge::perl
```
% wave --conda-package conda-forge::perl --freeze 
community.wave.seqera.io/library/perl:02a8b13c196e4274
```

**Comment by kchaung-lilly** [comment]
@munishchouhan Thanks, I was also able to create a container by removing the version tag. Just a heads up that the perl package available on the Seqera containers GUI only provides conda-forge::perl=STUB.

![image](https://github.com/user-attachments/assets/5e0890a2-ffc9-4cd2-b32a-88f19aed3336)

**Comment by munishchouhan** [comment]
> @munishchouhan Thanks, I was also able to create a container by removing the version tag. Just a heads up that the perl package available on the Seqera containers GUI only provides conda-forge::perl=STUB.

I have already raised the issue to the concerned team, they will look into it
