### ISSUE TITLE
Cleanup failed transfer pods  

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#590]
Container blobs are cached by running a K8s job with in turn create a pod to carry out the transfer operation. 

The current cleanup logic does delete the only the job and not the pods. 

https://github.com/seqeralabs/wave/blob/master/src/main/groovy/io/seqera/wave/service/blob/impl/KubeTransferStrategy.groovy#L96-L98

The goal of this issue is to delete also the pods when the job complete using the same deleting criteria.

**Comment by munishchouhan** [comment]
We are using `Backgroud` propogation policy where k8s deletes pods once the job is deleted
https://github.com/seqeralabs/wave/blob/e3b3d0278f603dcf8cc3ca4fea72baad803de57e/src/main/groovy/io/seqera/wave/service/k8s/K8sServiceImpl.groovy#L678
We can switch to `Foreground` propogation policy, where k8s will delete pods before deleting the job

**Comment by pditommaso** [comment]
Understand, agreed to change to `Foreground` policy
