### ISSUE TITLE
Add container describe endpoint 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#608]
The goal of this issue is to add a new endpoint that allow the retrieval of a container request meta-data. 

The endpoint is defined as such 

```
GET /v1alpha2/container/{token}
```

The response should return the [WaveContainerRecord](https://github.com/seqeralabs/wave/blob/c90411f0de4ba2716d3305a1c7ead1e6fc2bba19/src/main/groovy/io/seqera/wave/service/persistence/WaveContainerRecord.groovy#L43-L43) with the specified `token`

**Comment by munishchouhan** [comment]
containerId is present in buildRequest and not in WaveContainerRecord
https://github.com/seqeralabs/wave/blob/f844bec748e1d47ee4de4fe39055a48309800666/src/main/groovy/io/seqera/wave/service/builder/BuildRequest.groovy#L51

Currently we use token to get the WaveContainerRecord
Should we create new id for this?

**Comment by pditommaso** [comment]
I've used not the correct term. It should the container "token". Look here 

https://github.com/seqeralabs/wave/blob/c90411f0de4ba2716d3305a1c7ead1e6fc2bba19/src/main/groovy/io/seqera/wave/controller/ContainerController.groovy#L263-L263

and here

https://github.com/seqeralabs/wave/blob/c90411f0de4ba2716d3305a1c7ead1e6fc2bba19/src/main/groovy/io/seqera/wave/controller/ContainerController.groovy#L435-L435
