### ISSUE TITLE
Show list of build for a given containerId 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#693]
### Summary 

The buildId (e.g. `bd-8a141589f65e4838_1`) provided by Wave when building a container is made by three components: 
1. static prefix: `bd-` 
2. containerId: a unique checksum for generated Dockerfile and other metadata e.g. `8a141589f65e4838` 
3. build count: a progressive counter that represent how many times the build was tried e.g. `1` separated with a `_` character. 

### Use case   

In some cases it is useful to access to the list of builds for a given containerId e.g. `8a141589f65e4838` 

### Goal 

The goal of this issue is to extend the build view page so that if a partial (1) build id is provided a the list of builds matching the is shown reporting the following informations 

* buildId 
* digest
* buildTime
* status: succeeded or failed 
 

Once clicking on the buildId the page shows the classic build view. 

(1) in this context a "partial" should be interpreted as a complete containerId with our without prefix. For example given `bd-8a141589f65e4838_1`, the list should be should for `bd-8a141589f65e4838` or `8a141589f65e4838` any other substring should result in a "404 not found" error. 

### Implementation 

The logic for detecting partial buildId is already implemented [here](https://github.com/seqeralabs/wave/blob/17516ce7faaf7fbf5493c80112a42369fbcf1d6a/src/main/groovy/io/seqera/wave/controller/ViewController.groovy#L121-L130). Currently it's just looking up for the last complete buildId with that prefix. 

The logic should be changed so that all build records are loaded. If the resulting list size == 1, the redirect as now is done, if > 1 the list is rendered. 
 
The list html markup should go in a separate hbs template. The choose of the template to be used can be determined at runtime using `ModelAndView` response, see [here](https://micronaut-projects.github.io/micronaut-views/latest/guide/#views)

**Comment by ewels** [comment]
Would it be possible to also have an API endpoint for this, in addition to the HTML view?

**Comment by munishchouhan** [comment]
> Would it be possible to also have an API endpoint for this, in addition to the HTML view?

ok i will add that too

**Comment by pditommaso** [comment]
No please. the focus is the view. API is not the goal at this stage

**Comment by pditommaso** [comment]
API may require a different approach and design. We should also see in the context of Platform integration
