### ISSUE TITLE
Prevent empty nodes to render expand icon 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#694]
There's a minor inconsistency in the collapsible tree view rendered in the inspect page. 

In some cases empty nodes are rendered with a plus icon even if there's no content, instead of being disabled (see below). 

Likely this happens because there's empty object associated with it 

<img width="1379" alt="Screenshot 2024-10-16 at 10 19 49" src="https://github.com/user-attachments/assets/fc534661-32cb-4ea1-82df-df394f56445d">

**Comment by pditommaso** [comment]
Link to validate it https://wave.seqera.io/view/inspect?image=oras://community.wave.seqera.io/library/bwa:0.7.18--07d074a4d1589c42

**Comment by pditommaso** [comment]
This is still happening, check for example "annotations" [here](https://wave.seqera.io/view/inspect?image=195996028523.dkr.ecr.eu-west-1.amazonaws.com/wave/build:cowpy--7fc06d236d2b1db1&platform=linux/amd64)

**Comment by munishchouhan** [comment]
> This is still happening, check for example "annotations" [here](https://wave.seqera.io/view/inspect?image=195996028523.dkr.ecr.eu-west-1.amazonaws.com/wave/build:cowpy--7fc06d236d2b1db1&platform=linux/amd64)

ok, i will look into it

**Comment by munishchouhan** [comment]
PR to fix this issue:
https://github.com/seqeralabs/wave/pull/706
