### ISSUE TITLE
Show list of scan for a given partial scanId

### ISSUE THREAD

**Issue by munishchouhan** [seqeralabs/wave#698]
follow https://github.com/seqeralabs/wave/issues/693

**Comment by munishchouhan** [comment]
@pditommaso so in case of scan, should we return scans against partial scanId or against containerId?

like:
/view/scans/{partialScanId}
or
/view/scans/{containerId}/history

**Comment by pditommaso** [comment]
Let's use the same patter, we are using builds right now, therefore `/view/scans/{partialScanId}`

**Comment by munishchouhan** [comment]
@pditommaso is this correct?
![Screenshot 2024-10-18 at 08 17 42](https://github.com/user-attachments/assets/5e1f6840-acd9-46c4-a61b-c24610788a9d)

**Comment by pditommaso** [comment]
Fair enough!

**Comment by pditommaso** [comment]
Let's add a column on the right of "Status", named "Vulnerabilities" that reports the total count of issues found (irrespective of the level). If status is failed, then vulnerabilities contains `-`

**Comment by munishchouhan** [comment]
![Screenshot 2024-10-18 at 09 22 03](https://github.com/user-attachments/assets/82f32a61-3104-42dc-b072-7b3e05ff2d7d)

**Comment by pditommaso** [comment]
Nice!
