### ISSUE TITLE
Improve build history page

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#700]
The build history page could be improved as below: 

* Change the title to "Wave container builds history" 
* Render the following fields on to the history table 
  * Container image
  * Container format
  * Container platform 
* In the history table replaces "Container image" with "Container digest" 
* Make the `buildId` cell text not wrappable (i.e. text should stay in a single line)

**Comment by munishchouhan** [comment]
@pditommaso is this correct?
![Screenshot 2024-10-17 at 10 01 46](https://github.com/user-attachments/assets/7b465004-367e-4233-96e0-f011b6c0d1df)

**Comment by pditommaso** [comment]
I was thinking more the classic style for build view for top info 

<img width="750" alt="Screenshot 2024-10-17 at 10 44 37" src="https://github.com/user-attachments/assets/cad2faac-6a3f-4159-87d1-51cd43c920dd">

**Comment by munishchouhan** [comment]
ok understood

**Comment by munishchouhan** [comment]
like this?
![Screenshot 2024-10-17 at 11 18 20](https://github.com/user-attachments/assets/41d3e9e2-423a-4d2f-b66a-621dc8fc065c)

**Comment by pditommaso** [comment]
yes!
