### ISSUE TITLE
[Enhancement] - Redis Support encryption in transit 

### ISSUE THREAD

**Issue by gavinelder** [seqeralabs/wave#713]
## Background

Enterprise customers often leverage Redis within their environment and as such they may have a framework of best practices which redis deployments must adhere to such as the requirement for encryption in transit.

As Wave currently does not support encryption in transit the Redis deployment required for Wave does not meet existing requirements,  requiring customers  to carry out additional approvals and due diligence before it can be used.

## Requirements
- Enable TLS encryption for Redis connections
- Support customer-provided certificates
- Document configuration steps

## Success Criteria
- Redis connections use TLS 1.2+
- Customers can configure their own certificates

**Comment by pditommaso** [comment]
Available as of version [1.15.3](https://github.com/seqeralabs/wave/releases/tag/v1.15.3)
