### ISSUE TITLE
Conda lock file may not be rendered correctly 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#721]
The Conda lock file may not be collected correctly in some cases. 

In the following example the following content is reported as Conda lock file 

```
"     && cat environment.lock     && echo "
```

https://wave.seqera.io/view/builds/bd-1fc239026070d9d3_2

**Comment by munishchouhan** [comment]
I will look into it

**Comment by munishchouhan** [comment]
weird working in local:
<img width="864" alt="Screenshot 2024-10-28 at 15 25 09" src="https://github.com/user-attachments/assets/f31b23d7-6aaa-4922-bf4c-3b235809ed8c">

**Comment by munishchouhan** [comment]
ok i found the issue

the current approach has a bug
where if the image is cached, then the docker image won't run and therefore no condalock file in the logs
like in this case, first run has condafile

https://wave.seqera.io/view/builds/bd-1fc239026070d9d3_1

I will work on the fix
