### ISSUE TITLE
Error when there is a whitespace in container Image

### ISSUE THREAD

**Issue by munishchouhan** [seqeralabs/wave#755]
Wave is throwing error when there is a space left in container image name
```WARN  i.s.wave.core.RegistryProxyService - Unable to retrieve digest for image ' docker.io/hrma017/harshil-chai:latest' -- cause: java.net.URISyntaxException: Illegal character in authority at index 8: https:// docker.io/v2/```

**Comment by pditommaso** [comment]
Is there a more detailed error trace?

**Comment by munishchouhan** [comment]
this error is coming from here:

https://github.com/seqeralabs/wave/blob/63ff591465870797d2930672bcddbb26f5022c16/src/main/groovy/io/seqera/wave/controller/ContainerController.groovy#L425

here is more from log
```
2024-11-22 10:04:15.258	
09:04:15.258 [virtual-executor154579] WARN  io.seqera.wave.ErrorHandler - Container image ' docker.io/hrma017/harshil-chai:latest' does not exist or access is not authorized - Request: POST /v1alpha2/container
```

**Comment by pditommaso** [comment]
Solved by https://github.com/seqeralabs/wave/commit/1c36fd4c3e2f4aeb95b8d4a9fa2886e99f8ca672
